[package]
name = "pong"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "=0.13.0"
bevy-inspector-egui = "=0.23.4"
bevy_xpbd_2d = "=0.4.2"
rand = "=0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
